### ISSUE TITLE
[mentionSelect] function is not in the scope

### ISSUE THREAD

**Issue by ThangLeQuoc** [dmacfarlane/angular2-mentions#28]
I have the following code on HTML:
`< input [mention]="mentionParticipants" [mentionSelect]="mentioned"/>`

and in `component.ts` file , i have the following function for **mentioned** event

```
doDummy(){
    console.log('dummy called!');
  }


  mentioned(mention: string) {
    console.log('Mentioned: '+mention);
    //this.pushUserToMentionedList(mention);
    this.doDummy();
    return mention;
  }
```

but `doDummy()` is not detected in `mentioned()` function scope , as well as other variables in the file. 
![image](https://cloud.githubusercontent.com/assets/20574640/26025278/395b4bdc-380e-11e7-8207-c754bc0e5ccb.png)

Could you let me know how to fix this ?

**Comment by dmacfarlane** [comment]
The mentionSelect hook is intended to apply static formatting to selected mention values and it runs in the scope of the MentionDirective.

If you need to get a list of the mentions that have been entered, you should do it by parsing the input field value. It is the only reliable way, since the user can edit and remove mentions after they have been added.

**Comment by Anurag-Kashyap** [comment]
@dmacfarlane Hi, I'm using this package to tag users. On selecting I want to create an anchor tag with router-link to a particular page. Please help me in this regard. I have looking for it for a long time
